### ISSUE TITLE
Compare to autloaded WordPress too

### ISSUE THREAD

**Issue by szepeviktor** [swissspidy/compare-wp-performance#4]
Please consider adding my autoloaded core as an option.
https://github.com/szepeviktor/wordpress-autoloaded/blob/master/bin/remove-class-loading.sh
It is very straight-forward.
Needs Composer and
```json
    "config": {
        "classmap-authoritative": true
    }
```

**Comment by szepeviktor** [comment]
Oh noo!
This project is using `@wordpress/env` - which ignores that WordPress is written in PHP ...

Anyway ...
It is all up to you.
Autoloaded core runs in 10% less time.

**Comment by swissspidy** [comment]
The intention behind this repo is primarily to easily compare performance of a previous WP release with a newer one, not other kinds of setups. But I‘ll keep it in mind!

**Comment by szepeviktor** [comment]
All right.
I should realize few live in my golden cage where **everything** is given by default.
Total Control©️, PHP OPcache, Redis-based object cache, Composer.
